### ISSUE TITLE
Crash on using path tool

### ISSUE THREAD

**Issue by mestaritonttu** [pasbi/ommpfritt#113]
I tried the latest appimage https://github.com/pasbi/ommpfritt/releases/download/continuous/ommpfritt-0ea9218-x86_64.AppImage

Clicking in the viewport once with the path tool causes a crash.

Also, creating an ellipse and trying to move it causes a crash.

I tried to build it myself earlier, but ran into some linking issue (I'm not at my usual workstation atm, so unable to quote).

**Comment by pasbi** [comment]
Thanks for reporting.
I can reproduce the described issue from the appimage executable only, the locally compiled executable from code at the same commit (0ea92185e98d7c27c63da93dc963978a5aeeebfe) works like a charm.
