### ISSUE TITLE
Path Tool Usability: Tangent directionality

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#133]
Hey there,

I'd like to propose a usability-related suggestion, namely to invert the tangent directionality of the path tool during creation of new vertices.

Consider this diagram - it indicates 2x2 different paths (black lines) with 3 vertices (black squares) and the mouse movement patterns required to draw the respective paths, both in the way it is currently required (red lines) and in the way I believe would be more benefical (blue lines). Dashed colored lines indicate passive mouse movement, solid colored lines indicate where a click-and-drag happens, along with an arrow cap to indicate directionality:

![handles](https://user-images.githubusercontent.com/13210/101282631-86db9a80-37d6-11eb-94e1-00a10fbc16bd.png)

I'm proposing this because I believe the suggested interaction pattern offers more natural usablity (because the direction in which the tangents are "drawn out" follows the direction of the curve forward, and the overall mouse pattern also fits and follows the general rhythm of the curve - as one experiences it when drawing a curve with a pencil!), as well as more efficient (for flat curves the mouse distance traveled is almost twice as long in the currently required interaction pattern because one needs to zig-zag back and forth - which is also physically much less comfortable than a straight, flowing hand motion).

If anything is unclear about the proposal itself, do let me know! :+1:

**Comment by pasbi** [comment]
Thanks for the suggestion and the nice drawing. I appreciate it very much :smiley:!
I have this on my list for a very long time, it's good to have an issue about it now.
Not sure when I will fix it, it's low prior atm. PR welcome, it shouldn't be very hard.

**Comment by simonrepp** [comment]
If low priority implies that this might be on your list for yet another "very long time" ;) I would - as a potential user - like to emphasize that it's these details that might be (and probably are) keeping potential users from actually using ommpfritt - even from looking into it really. I think you've built something quite impressive here with omm and I see a good chance that a lot more people than right now will realize this at some point, but ultimately *if* getting traction, users, contributors, donations, funding ... is on your wishlist I think it's strategically vital to identify and resolve such things (which are so much more prohibitive to user adoption than they are complex to implement!).

I generally hold back on these "hey as a user I need XY" things (and I did for omm so far), because being a voluntary FOSS developer myself I know that it might be more annoying than helpful if the dev already has an agenda for where to go, but seeing this issue here classified as low priority (and apparently since a long time already) I feel it important to restate this: *If* user adoption is among your goals, allocate some resources to it! It will pay back - figuratively, and maybe also financially at some point if you want and make it so ... :)

**Comment by pasbi** [comment]
I appreciate your comment and I cherish that you foresee such a prospering future.
That feels great :partying_face: 

Currently, my priority is making the code better (maintainable, cleaner, using static checkers and tests).
That's working under the hood that the user will not (immediately) benefit from (see  #131).
The second is fixing some severe issues on Windows (like an immediate crash if you change a scalar field).

I don't want to discuss the priorities, but I think having a good Windows build is also key for a broad user base, as most people use it.

One last point: I'm currently the only developer. I'm not sure for how long this is continuing to work.
I appreciate any interaction, **but I'm really hoping to find some long-term collaborators soon**.
I think these are the kind of issues that attract such people: Low hanging fruits that have a big impact.
Ok, that sounds like I don't fix bugs just to attract developers: *that's not the case*, but I think you get the point.

**Comment by pasbi** [comment]
I've just had a brief look into the code and I think this issue can be solved by just switching two `-`-signs.
Would you consider to open a PR for that?
I could assist you if you have trouble building the project (not sure about your experience).
As I said: I'm looking for co-developers :grin: 

If you feel uncomfortable, I think I can fix the issue within the next week.

**Comment by simonrepp** [comment]
Thanks for your detailed reply!

Some notes/thoughts in random order:
- Fixing immediate crashes for a potentially large userbase is of course vital, no objections there :)
- To clarify, I'm not *foreseeing* this prosperous future, I just wanted to make sure you're fully aware (if you aren't already anyhow of course :)) that there is a very real chance of success for omm and that it's not magic: Make something that people love to use, greatly help them to discover that fact, and they will use it! And for that it's essential to not lose sight of the fact that as developers we're usually unaware of what our users *really* need in practice, and therefore imperative to attentively evaluate and prioritize user feedback that comes in, otherwise the agenda might be off - our project gets better and better, but somehow nobody seems to notice or care, and thus at some point we don't either ... 
- I get your notion behind leaving "easy PRs" lying around for new developers (it's a perfectly valid approach), but don't do this with basic, critical features! :) For every new developer that you *might someday* (TM) pick up through this, you're alienating potential or existing users by the dozens on a daily basis, however long the issue lies around, so, it really does not add up. Pick some generic or exotic nice-to-have feature that is easy to implement instead, or some cosmetic change without UX impact, etc.
- Regarding collaborators: Letting easy PRs lie around is more of a chance approach. These usually get picked up by people who have time and curiosity, who do the PR because it's easy and it satifies their curiosity and their wish to contribute just *something* (not caring what it is really). There are cases where this develops into a long-term collaboration (because people randomly stick with it and grow into the project), but in principle the developer is tied to the project just out of chance, which is not a strong tie ...
- Regarding collaborators pt. II:  I'd argue the sort of contributors one really wants are those that take on PRs regardless of the difficulty label but based solely on the task, those that have a strong emotional or professional involvment that a specific feature should exist or a specific bug should not. And those will stay not by chance, but because the only reason they even got into their first PR was their intention to stick to the project long-term. And here's the crux: These people have to be devoted *users* of your software (or employed for someone who is), so make sure to convince users today, for they might be your co-developers tomorrow.
- Regarding `I'm currently the only developer. I'm not sure for how long this is continuing to work.` - I'm aware, and it's precisely why I'm writing all this. If no one uses omm you'll have neither motivational support nor financial support, this usually does not work out long-term, obviously. Thus the only logical approach to making a project like that sustainable is to prioritize stuff that is relevant for your users: Proactively ask them what they think, listen and act when they tell you (which is not to say do just anything they ask, but carefully consider and make good plans based on it :))

:+1:

**Comment by simonrepp** [comment]
Regarding the PR - thanks for checking, I'd rather you commit the change, because right now it'd just take me comparatively forever to hunt down the two minus signs, while checking and processing my PR probably amounts to a good portion of the time it'd take you do the commit yourself anyway, so it wouldn't really help either of us ... :)

On a personal note regarding my contribution perspective: I have my own set of FOSS projects to develop and maintain for the forseeable future, but if I should feel compelled to get something specific into omm at some point in the future there's a chance I will. (even despite the fact that I'm not much into C++ these days :)) I've been promoting omm to my community and peers occasionally over the last year because I see a great opportunity for omm to establish itself as another libre vector staple (and as I mentioned I'm impressed with how much work you have already put into this, really cool), but to be fully open about this part also: As a *user* I'm not yet convinced that omm fulfills its own claims right now, as I see a lack of prioritization to some basic usability things that for me currently renders it unusable for producing things at the level of detail and quality I intend for (given a reasonable investment of time). I also haven't seen any sufficiently complex result produced with omm yet (artwork, animation, design), which adds to my skepticism currently. Don't take this the wrong way though: All of these details might lie just around the corner, much of it is probably trivial to implement, it just hasn't been done yet, and I wanted to give you a nudge in that direction also with this ticket here. As soon as I get the feeling I can actually build the things I need to build in omm I would be very interested and up for contributing user documentation, complex examples (artwork/design), possibly screencasts/tutorials and such, much rather than code actually. Ideally I'd like to see *you* succeed with this and get donations (or better yet steady funding) asap, so omm sustains itself and any additional developer is just bus-factor reduction and feature icing on top of the cake. May omm prosper :+1:

**Comment by pasbi** [comment]
> Regarding the PR - thanks for checking, I'd rather you commit the change, because right now it'd just take me comparatively forever to hunt down the two minus signs, while checking and processing my PR probably amounts to a good portion of the time it'd take you do the commit yourself anyway, so it wouldn't really help either of us ... :)

Of course you will take longer. It'd be very surprising (and creepy) if you wouldn't :laughing: 
It'd also be more work for me to supervise and assist you than doing it myself (took less than a minute).
But my hope is that supervising/assisting pays out in the long term :grin:

**Comment by simonrepp** [comment]
Haha I find the image of the creepy codevoyeur quite amusing, thanks for that :)
And thanks so much for the super quick action, I'm sure many people are going to love this small change!
