### ISSUE TITLE
Vertices Selection Usability: More consistent and efficient context-click behavior

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#134]
Hi again!

Here are two more super effective opportunities for you to win over interested users with most likely absolutely minimal coding effort:

### Path Tool

**Steps**: `Select 2+ vertices` -> `Right-click *on one of the selected* vertices`

**Current Behavior**: The selection is reduced to just the vertex which has been right-clicked

**Proposed Behavior**: The selection is kept so the context action can be applied to all selected vertices (this behavior already exists in omm when the same steps are done with the `Select Points Tool` - this would therefore also bring consistency)

**Note**: The behavior when clicking on **one of the unselected** vertices (discards selection and selects only that vertex) makes perfect sense and should be kept (just a heads up as that might be inadvertently affected by changes here I guess).

### Select Points Tool

**Steps**: `Select 2+ vertices` -> `Right-click into an empty area of the viewport`

**Current Behavior**: The selection is discarded - all context actions but `Select All` become useless

**Proposed Behavior**: The selection is kept so the context action can be applied to all selected vertices (this behavior already exists in omm when the same steps are done with the `Path Tool` - this would therefore also bring consistency)

### Screencasts

Just in case the textual description is unclear here are two tiny screencasts that demo the current behavior for which the changes are proposed: [demo_screencasts.zip](https://github.com/pasbi/ommpfritt/files/5652879/demo_screencasts.zip)

Thanks for your dedication Pascal - Path tool with inverted tangents is already so much more usable now, really great! :+1:

**Comment by pasbi** [comment]
Please don't hesitate to reopen if you find something to improve.
A good selection behaviour is complex to design, hard to test and crucial for UX.
Appreciate any comments.

**Comment by simonrepp** [comment]
Cool thanks for the numerous improvements and for reaching out for feedback :+1: 

For now, since this morning, all builds segfault for me on startup unfortunately. I tried it on Arch earlier and now (`ommpfritt-a02bb145-x86_64.AppImage` and building the AUR package from source [`ommpfritt-7d93e566c251d28a19e9`]). I also just reproduced this on Ubuntu 20.04 as well with the `ommpfritt-a02bb145-x86_64.AppImage` - same result. If you don't get this error on your system I can offer to build a debug version and see if I get a reasonable identification of the line/file which triggers this.

**Comment by pasbi** [comment]
I cannot reproduce the described behaviour (Arch and Ubuntu 20.04 VM).
Could you please open a new issue? It'd be awesome if you could give me a backtrace!
(relevant: #140 )

**Comment by simonrepp** [comment]
Sure, will look into it asap!

**Comment by pasbi** [comment]
I think I know what happens.
Please remove the config file `~/.config/omm/ommpfritt.conf`.

**Comment by simonrepp** [comment]
That worked, thanks :)
