### ISSUE TITLE
Color selector dialog sends omm into endless loop

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#141]
Steps:
1.Create a new Style
2. Select it in Style Manager
3. Double click Pen or Brush Color field in Properties panel
4. Black window of death opens

(Note that it also happens if the style is already assigned to a rectangle, for instance)

Getting this with today's latest omm from the official AppImage or a self-built omm, both on Arch.

If not reproducible I can again offer to try to isolate this somewhat in a Debug build.

![out](https://user-images.githubusercontent.com/13210/102106681-27623800-3e31-11eb-8790-5cc9f1568b87.gif)

**Comment by pasbi** [comment]
Thanks, I can reproduce it.

**Comment by simonrepp** [comment]
Thanks and no worries, don't mind reporting these for now. :)
