### ISSUE TITLE
missing libraries in the windows installer

### ISSUE THREAD

**Issue by vincent456** [pasbi/ommpfritt#170]
I tried to install the program from the windows installer and I encounter an error saying that zlib1.dll is missing.

**Comment by pasbi** [comment]
Hi vincent, thanks for your interest and your comment!

I hope that I can look into this over the weekend.

**Comment by pasbi** [comment]
@vincent456 does this installer work?

https://github.com/pasbi/ommpfritt/suites/3518933891/artifacts/84025231
