### ISSUE TITLE
Cannot specify sources for target "libommpfritt" which is not built by this project

### ISSUE THREAD

**Issue by mestaritonttu** [pasbi/ommpfritt#200]
On Arch Linux I try to build with

`cmake -S ./src -B /home/tonttu/ommpfritt-build`

but I get many instances of this error:
```
CMake Error at animation/CMakeLists.txt:1 (target_sources):
  Cannot specify sources for target "libommpfritt" which is not built by this
  project.
```

What to do?

**Comment by pasbi** [comment]
The source directory must be the root of the repository, in your case most likely `.`

**Comment by mestaritonttu** [comment]
Thanks, I was able to build now
