### ISSUE TITLE
Select by point normal

### ISSUE THREAD

**Issue by mestaritonttu** [pasbi/ommpfritt#74]
This feature would allow to select points (or edges, if edge mode is accepted) by similarity of their normals, working from an initial selection. The tolerance for the similarity could be adjusted.

For some reference and terminological nitpicking: https://gamedev.stackexchange.com/questions/160344/algorithms-for-calculating-vertex-normals-in-2d-polygon
From an answer:
> What you call the vertex normals are not normals. They are the bisectors of the normals of the two adjoining sides.

**Comment by pasbi** [comment]
probably fixed in a8cc101dfbaab4f078f756d22858843a548338c3.
I know "select by similar normal"-tools only to select (linear) polygon modeling. It's not trivial to translate the concept to (nonlinear) paths.
I hope the tool suits your needs, feel free to reopen if you think the tool can be improved.
