### ISSUE TITLE
Bridge tool

### ISSUE THREAD

**Issue by mestaritonttu** [pasbi/ommpfritt#75]
Select two non-neighbouring sets of points (or edges if edge mode is accepted) and connect them. Allow to interactively adjust the subdivision and curvature of the created bridge.

Implementation in Modo: https://learn.foundry.com/modo/content/help/pages/modeling/duplicate_geometry/bridge.html

**Comment by pasbi** [comment]
omm can only handle paths, no polygons.
Polygons are a rather exotic concept in 2d world. Currently I don't plan to implement polygons.

I don't understand the benefit of the proposed feature for paths. Feel free to reopen the issue and explain your thoughts more thoroughly.

**Comment by mestaritonttu** [comment]
Is it really so that this sort of end result can only be achieved with polygons? Sorry for being a bit ignorant on the math involved :(

**Comment by pasbi** [comment]
it's not a mathematical problem, but rather the concept does not really fit, does it?
A point on a path can have zero (degenerated), one (start/end) or two neighbor points.
That is, two sets of points could only be connected, if these points were degenerated or end points.
A T-connection or X-connection is just not possible with paths.

I will, however, implement tools to join to paths into one.

**Comment by mestaritonttu** [comment]
Yes, sorry, I get it now after doing some tests in practice.

**Comment by pasbi** [comment]
After thinking a bit about this, I think it'd be great to have some kind of "advanced paths", i.e.,  a set of connected points where each point can have more than two neighbors.

It'd be similar to polygons but not quite the same.
- Non-closed paths/subpaths are allowed (imagine a cross with one center point and four arms)
- non-straight edges would be great (using, e.g., bezier-interpolation)

That'd be a fundamentally new concept, which would be a huge amount of work to implement, but it might be worth it.
Do you know if such a structure already exists in other applications? I don't even know how to call such a thing. Maybe 'Poly Path'? 'Polygon Curve'?

**Comment by mestaritonttu** [comment]
Yes, I know actually :) It is the reason I started thinking about the possibility to bring 3D-inspired concepts to 2D editing. Figma devs implemented it and call it "vector networks": https://www.figma.com/blog/introducing-vector-networks/

> A vector network improves on the path model by allowing lines and curves between any two points instead of requiring that they all join up to form a single chain.

**Comment by mestaritonttu** [comment]
Adding a comment to this as I had overlooked an existing open source tool which, like Figma, has a novel approach to geometry: https://github.com/dalboris/vpaint

They are currently running a Kickstarter to move from prototype to product and in [a comment](https://www.kickstarter.com/projects/vgcsoftware/vgc-illustration-the-drawing-app-of-the-future/comments?comment=Q29tbWVudC0zNDA3NDE0Ng%3D%3D&reply=Q29tbWVudC0zNDA3NjYxOQ%3D%3D) the creator says:

> Figma is the only other tool I know which has a somewhat similar feature (called "Vector Networks"), although their implementation is not quite as complete as in our prototype, and Figma is focusing on using control points rather than hand-drawn lines you can sculpt. So there are shared ideas, but overall a very different user interface and experience.

**Comment by pasbi** [comment]
That looks pretty awesome.
Thanks for sharing. Maybe I'll try to implement something like that soon.

**Comment by pasbi** [comment]
@mestaritonttu  please see #199 for a first draft

**Comment by mestaritonttu** [comment]
Hmm, shouldn't this be kept open until there is an actual bridge tool?
