### ISSUE TITLE
Extend geometry

### ISSUE THREAD

**Issue by mestaritonttu** [pasbi/ommpfritt#77]
1. Select two or more points
2. Invoke tool
3. Use manipulation widgets to translate/rotate/scale the new geometry

Modo tool as a reference: https://learn.foundry.com/modo/content/help/pages/modeling/vert_edge_poly_comp_tools/edge_extend.html

**Comment by pasbi** [comment]
omm can only handle paths, no polygons.
Polygons are a rather exotic concept in 2d world. Currently I don't plan to implement polygons.

I don't understand the benefit of the proposed feature for paths. Feel free to reopen the issue and explain your thoughts more thoroughly.
