### ISSUE TITLE
"make install" does not work

### ISSUE THREAD

**Issue by probonopd** [pasbi/ommpfritt#79]
Succeeded building ommpfritt following the instructions. But now then getting `make: *** No rule to make target 'install'.  Stop.`

https://travis-ci.com/probonopd/ommpfritt/builds/117334276#L2180

Could you please support `make install`, including a desktop file and icon?

Thanks.

**Comment by pasbi** [comment]
is this still relevant?
A desktop file exists, you can find the icon under ommpfritt/icons/omm.png

**Comment by probonopd** [comment]
Yes, I have made crude workarounds but it would be good if `make install` would properly install those things.

**Comment by pasbi** [comment]
There are currently only two files to install: the executable and a library.
So I think that installing is trivial?

Please tell me if it works for you and reopen this issue, if necessary.

**Comment by probonopd** [comment]
Agree, not a big deal. Nevermind, I was easily able to work around it.
