### ISSUE TITLE
Cyclic instancing through select box triggers instant/near-instant crash

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#81]
Chances are you are aware of this but I've found #60 (to be closed) so maybe it slipped under the radar :)

If I use the `Reference` select box in the `Instance` properties tab I can self-instance an instance. This triggered an instant crash the first time I did it, and an near-instant crash the second time (took another operation to trigger the deathly update cycle or something :)).

If it's cheap to implement, not making the instance show up in it's own instancing choices is probably the solution users will appreciate most (more than being able to make the non-sensical choice without a crash) :)

![Screenshot from 2019-08-02 19-04-37](https://user-images.githubusercontent.com/13210/62386788-1f199d80-b559-11e9-823e-60c3da9be04d.png)

**Comment by simonrepp** [comment]
Also I promise something more relevant for the next issue, it was just too tempting to try and see what happens when I saw the self-instancing choice, apologies :) ommpfritt looks really promising and I look forward to playing around some more with it! Thanks!!

**Comment by pasbi** [comment]
Thanks for reporting this.
I'm currently designing the whole update-mechanism from scratch.
(That's one of the two reasons why there hasn't been any update since few months).
So I will not quick-fix this, but rather once the new update-mechanism is ready.

**Comment by simonrepp** [comment]
Sounds good! I would do it no different :) I've already discovered some issues with the updating but I'll spare you the reports then if you're working on that anyway ;)

**Comment by pasbi** [comment]
See also #68

**Comment by pasbi** [comment]
I think the update-mechanism should be fixed now. I appreciate tests and bug reports.

**Comment by simonrepp** [comment]
Very cool, thanks!! I'll report them if I find remaining issues here!
