### ISSUE TITLE
Crash on opening icons/icons.omm

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#87]
Hey again, :wave: 

In the most recent continuous build (22a02bd) omm crashes when opening the `icons/icons.omm` file found in the omm repository itself.

Back in the continuous build version I first downloaded on August 2nd (d75e85a) it does open without issues.

I wanted to see if I can get some insight on where the segfault occurs myself first but curiously the `Open`, `Save`, etc. dialogs don't show in my debug build, the window just dims, which shows the GUI is doing something there, but the modal dialog itself does not appear. Probably this is something related to my debug build/specific setup though, because in the continuous build versions the dialogs work just fine. (If you have some idea on this let me know, it's more of a side note though)

Thanks, and great to see the recent progress by the way! :tada:

**Comment by pasbi** [comment]
Do you use Windows, Unity or a non-default skin?

**Comment by pasbi** [comment]
> In the most recent continuous build (22a02bd) omm crashes when opening the icons/icons.omm file found in the omm repository itself.

fixed in e8d967

**Comment by simonrepp** [comment]
I'm using Ubuntu 19.04 with stock gnome, with the `yaru-dark` application theme variant. If by skin you mean the light/dark switch inside omm, I tried that out but if I recall correctly the invisible modal issue occurred with both the default/light and the dark theme active.

I'll try it again with beforehand switching to the default Yaru application theme when I get to it, if that is maybe a factor here. :)

Thanks for the quick icons.omm fix!

**Comment by simonrepp** [comment]
Tried with the default Yaru theme and with light/dark/default skin, all the same. I'll keep you posted if I get behind this at some point! :)
