### ISSUE TITLE
Opening icons/icons.omm fails again

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#88]
Impressive pace of development, these constant updates spark a lot of joy. :)

I am reporting a reappearing regression: At the latest commit d826293 (both in the continuous build and when I build myself) omm cannot open `icons/icons.omm`.

![Screenshot from 2019-11-03 14-01-52](https://user-images.githubusercontent.com/13210/68085622-1def5980-fe43-11e9-8bad-01f9a9cf40d3.png)

Thanks for your efforts!

**Comment by pasbi** [comment]
Thanks for the report! I used the opportunity to make the serialization more efficient:

fixed in e719ea7db834bdf6cbad42a2cc65623e69d948fa

I will push later ...
