### ISSUE TITLE
Non-default mouse-based viewport navigation preferences not working

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#91]
I was playing around with the viewport navigation preferences and noticed that apparently `left` or `middle` mouse based configurations do not work, just in case this is unintentional (vs. just not yet implemented) I thought I'd report it. :) These e.g. don't work at all (i.e. nothing happens when I use the configured mouse-key-combination in the viewport), but I suppose others don't either:

![Screenshot from 2019-11-08 11-01-52](https://user-images.githubusercontent.com/13210/68468009-7cd41a80-0217-11ea-8489-4879b0ce023b.png)

![Screenshot from 2019-11-08 11-03-24](https://user-images.githubusercontent.com/13210/68468016-7fcf0b00-0217-11ea-95b4-fb481d689568.png)

**Comment by simonrepp** [comment]
I'm also curious if you already have some plan what defaults for panning/zooming you want to establish in the long run? (are the current ones very intentional already or just merely placeholder configuration that came up during development?)

To give some user feedback as well, I was a bit confused if panning/zooming were available at all and didn't find the actual working combination through trial and error (only by looking into the preferences). The first things I tried were middle-mouse + shift/ctrl combinations (which coming from a blender/inkscape/krita background are the defaults I'm accustomed to). I then tried combinations involving left mouse, and apparently my brain discarded right mouse as a possiblity for this entirely, not sure why to be honest, guess my intuition just decided it that way even if rationally it sounds like the only logical third option to try. :)

Also to me personally `Pan` would be more recognizable than `Shift` but maybe this is bias from my usual tools and `Shift` is well established in other packages ... just noting it here for consideration.

**Comment by pasbi** [comment]
> I'm also curious [...] defaults for panning/zooming [...]came up during development?)

They're intentional. I believe it's what Cinema4D also defaults to. However, I was aware that most Linux desktop environments use Alt + Drag-Left/Right to move/(scale?) windows, hence a conflict is quite likely. That is, btw, the reason why I added these preferences now.
There are probably thousand "standard" key mappings for this, I'm open to discuss the default to find the best fist for *most* people.

> To give some user feedback as well, I was a bit confused [...] to try. :)
Yes, I've already seen this coming. I'd like to say it's your fault but it isn't. The app was designed to be usable intuitively. Not being able to zoom/pan possibly will daunt users, so you're very welcome to propose improvements.

> Also to me personally Pan would be more recognizable than Shift  [...]
Your right. It's an inconsistency. Sometimes it's called pan, sometimes shift. Both are fine with me as long as it is consistent. You're welcome to propose a PR (rename variables, functions, literals and update translation files) or open an issue.

**Comment by pasbi** [comment]
> I was playing around with the viewport navigation preferences and noticed that apparently left or middle mouse based configurations do not work, just in case this is unintentional (vs. just not yet implemented) I thought I'd report it. :) These e.g. don't work at all (i.e. nothing happens when I use the configured mouse-key-combination in the viewport), but I suppose others don't either:

It's probably a conflict with other keybindings (omm or your desktop environment). It looks like you're using gnome3?

**Comment by simonrepp** [comment]
Regarding the defaults and the terminology I'm absolutely fine with whatever you want to go with, that there is a consideration behind each decision is really all I wanted to know, the rest is UX design research of which you now have another sample to base your decisions on in the future. (and as you remark, more will come :))

**Comment by pasbi** [comment]
It was a bug indeed (some stupid typo). Thanks for reporting!

**Comment by simonrepp** [comment]
I'm a bit skeptical about the keybinding conflict theory - I'm using any number of `Left/Middle Click` + `Modifier` combinations in blender and inkscape and so on and there's no issues there, so if at all I would guess maybe it conflicts with omm defaults, but even then 4 conflicts seems like a lot. I'll check this right now in the preferences. :)
